--CREAR TABLA EMAIL---
CREATE TABLE email(
    direccion VARCHAR(50),
    persona VARCHAR(255)
);

--AÑADIDO IDENTIFICADOR--
ALTER TABLE emails
ADD COLUMN identificador INT AUTO_INCREMENT PRIMARY KEY FIRST;

SHOW TABLES;
